{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%gui qt5\n",
    "import torch\n",
    "import torchio as tio\n",
    "from torch.utils.data import DataLoader\n",
    "import scipy.io\n",
    "from scipy.ndimage import maximum_filter\n",
    "import pandas as pb\n",
    "import numpy as np\n",
    "import napari"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Generation of training data"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We have volumes of micro-ct data that we are trying to label. However, the labels we currently have are 3d point locations, which isn't a format that our deep learning model can link spatially to our ct data. \n",
    "\n",
    "We want to convert these 3d point locations into a new \"prediction volume\". This is what we want our deep learning model to end up producing. It is also a format that our deep learning model can read, link spatially to our data and produce."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Let's first set up some helper functions to generate annotated prediction volumes for our analysis."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def _load_point_data(dir):\n",
    "    print('loading point data from .mat files...')\n",
    "    # load classifications\n",
    "    mat = scipy.io.loadmat(dir)\n",
    "    classification = pb.DataFrame(\n",
    "        mat['save_dat'][0]['data'][0][0][0][0]).iloc[:, 5]\n",
    "    points = pb.DataFrame(\n",
    "        mat['save_dat'][0]['data'][0][0][0][0]).iloc[:, [2, 1, 0]]\n",
    "    points.columns = ['x', 'y', 'z']\n",
    "    # convert back to numpy array and round to nearest voxel\n",
    "    points = np.array(points)\n",
    "    points = np.round(points).astype(int)\n",
    "    # get corneas and rhabdom locations with x, y and z data\n",
    "    cornea_indx = (classification == 0) | (classification == 2)\n",
    "    rhabdom_indx = (classification == 1) | (classification == 3)\n",
    "    cornea_locations = points[cornea_indx, :]\n",
    "    rhabdom_locations = points[rhabdom_indx, :]\n",
    "\n",
    "    return cornea_locations, rhabdom_locations\n",
    "\n",
    "def _point_to_segmentation_vol(image, cornea_locations, rhabdom_locations):\n",
    "    print('converting point data to segmentation volume...')\n",
    "    # create empty matrix the size of original data\n",
    "    empty = image.copy()\n",
    "    empty[:, :, :] = 0\n",
    "    \n",
    "    corneas = empty.copy()\n",
    "    rhabdoms = empty.copy()\n",
    "    \n",
    "    corneas[\n",
    "        0,\n",
    "        cornea_locations[:, 2],\n",
    "        cornea_locations[:, 1],\n",
    "        cornea_locations[:, 0]\n",
    "    ] = 1\n",
    "    rhabdoms[\n",
    "        0,\n",
    "        rhabdom_locations[:, 2],\n",
    "        rhabdom_locations[:, 1],\n",
    "        rhabdom_locations[:, 0]\n",
    "    ] = 1\n",
    "    \n",
    "    # now use a maximum filter to make points a slightly larger area\n",
    "    # note, that maximum filter makes predictions a cube without rounded edges\n",
    "    # a gaussian filter may be more appropriate\n",
    "    corneas = maximum_filter(corneas, size=15)\n",
    "    rhabdoms = maximum_filter(rhabdoms, size=15)\n",
    "\n",
    "    # now merge both into a single prediction volume\n",
    "    # 0 = nothing\n",
    "    # 1 = cornea\n",
    "    # 2 = rhabdom\n",
    "    prediction = empty\n",
    "    prediction[corneas > 0] = 1\n",
    "    prediction[rhabdoms > 0] = 2\n",
    "    \n",
    "    return prediction\n",
    "\n",
    "def create_annotated_volumes(dir, image):\n",
    "    cornea_locations, rhabdom_locations = _load_point_data(dir)\n",
    "    annotated_vol = _point_to_segmentation_vol(\n",
    "        image,\n",
    "        cornea_locations,\n",
    "        rhabdom_locations\n",
    "    )\n",
    "    print('done.')\n",
    "    return annotated_vol\n",
    "    "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Let's load our mct volumes and point data to make segmentation labels for training"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: In /tmp/SimpleITK-build/ITK-prefix/include/ITK-5.2/itkImageSeriesReader.hxx, line 480\n",
      "ImageSeriesReader (0x5c86430): Non uniform sampling or missing slices detected,  maximum nonuniformity:7.46568e-06\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "loading point data from .mat files...\n",
      "converting point data to segmentation volume...\n",
      "done.\n"
     ]
    }
   ],
   "source": [
    "id = 'P_crassipes_FEG191022_077A'\n",
    "img_dir = '//media/jake/1tb_ssd/mctv_analysis/head_scans/P_crassipes_FEG191022_077A_highpriority'\n",
    "matlab_ann_dir = '//media/jake/1tb_ssd/mctv_analysis/mctv_resfiles/hyperiids/P_crassipes_FEG191022_077A/P_crassipes_FEG191022_077A.mat'\n",
    "labels_dir = '//media/jake/1tb_ssd/mctv_analysis/labels/'\n",
    "\n",
    "transform = tio.ToCanonical()\n",
    "img = tio.ScalarImage(\n",
    "    img_dir\n",
    ")\n",
    "ann = tio.LabelMap(\n",
    "    tensor=create_annotated_volumes(\n",
    "        matlab_ann_dir,\n",
    "        img.data.numpy()\n",
    "    )\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "viewer = napari.Viewer()\n",
    "viewer.dims.ndisplay = 3 # toggle 3 dimensional view\n",
    "viewer.add_image(img.data.numpy())\n",
    "viewer.add_image(ann.data.numpy())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Let's double check that the affine matrices are the same"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[-0.00287747,  0.        ,  0.        ,  0.        ],\n",
       "       [ 0.        , -0.00287747,  0.        ,  0.        ],\n",
       "       [ 0.        ,  0.        ,  0.00287747,  0.        ],\n",
       "       [ 0.        ,  0.        ,  0.        ,  1.        ]])"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Error drawing visual <Volume at 0x7fa94c0b1e50>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/app/backends/_qt.py\", line 846, in paintGL\n",
      "    self._vispy_canvas.events.draw(region=None)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 218, in on_draw\n",
      "    self._draw_scene()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 277, in _draw_scene\n",
      "    self.draw_visual(self.scene)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 315, in draw_visual\n",
      "    node.draw()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/visuals.py\", line 99, in draw\n",
      "    self._visual_superclass.draw(self)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/visuals/visual.py\", line 451, in draw\n",
      "    self._program.draw(self._vshare.draw_mode,\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/visuals/shaders/program.py\", line 102, in draw\n",
      "    Program.draw(self, *args, **kwargs)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/program.py\", line 526, in draw\n",
      "    canvas.context.flush_commands()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/context.py\", line 172, in flush_commands\n",
      "    self.glir.flush(self.shared.parser)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 579, in flush\n",
      "    self._shared.flush(parser)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 501, in flush\n",
      "    parser.parse(self._filter(self.clear(), parser))\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 819, in parse\n",
      "    self._parse(command)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 775, in _parse\n",
      "    raise RuntimeError('Cannot %s object %i because it '\n",
      "RuntimeError: Cannot SIZE object 31 because it does not exist\n",
      "WARNING: Error drawing visual <Volume at 0x7fa94c0b1e50>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/app/backends/_qt.py\", line 846, in paintGL\n",
      "    self._vispy_canvas.events.draw(region=None)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 218, in on_draw\n",
      "    self._draw_scene()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 277, in _draw_scene\n",
      "    self.draw_visual(self.scene)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 315, in draw_visual\n",
      "    node.draw()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/visuals.py\", line 99, in draw\n",
      "    self._visual_superclass.draw(self)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/visuals/visual.py\", line 451, in draw\n",
      "    self._program.draw(self._vshare.draw_mode,\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/visuals/shaders/program.py\", line 102, in draw\n",
      "    Program.draw(self, *args, **kwargs)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/program.py\", line 526, in draw\n",
      "    canvas.context.flush_commands()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/context.py\", line 172, in flush_commands\n",
      "    self.glir.flush(self.shared.parser)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 579, in flush\n",
      "    self._shared.flush(parser)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 501, in flush\n",
      "    parser.parse(self._filter(self.clear(), parser))\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 819, in parse\n",
      "    self._parse(command)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 775, in _parse\n",
      "    raise RuntimeError('Cannot %s object %i because it '\n",
      "RuntimeError: Cannot SIZE object 31 because it does not exist\n",
      "WARNING: Error drawing visual <Volume at 0x7fa94c0b1e50>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/app/backends/_qt.py\", line 846, in paintGL\n",
      "    self._vispy_canvas.events.draw(region=None)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 218, in on_draw\n",
      "    self._draw_scene()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 277, in _draw_scene\n",
      "    self.draw_visual(self.scene)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 315, in draw_visual\n",
      "    node.draw()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/visuals.py\", line 99, in draw\n",
      "    self._visual_superclass.draw(self)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/visuals/visual.py\", line 451, in draw\n",
      "    self._program.draw(self._vshare.draw_mode,\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/visuals/shaders/program.py\", line 102, in draw\n",
      "    Program.draw(self, *args, **kwargs)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/program.py\", line 526, in draw\n",
      "    canvas.context.flush_commands()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/context.py\", line 172, in flush_commands\n",
      "    self.glir.flush(self.shared.parser)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 579, in flush\n",
      "    self._shared.flush(parser)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 501, in flush\n",
      "    parser.parse(self._filter(self.clear(), parser))\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 819, in parse\n",
      "    self._parse(command)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 775, in _parse\n",
      "    raise RuntimeError('Cannot %s object %i because it '\n",
      "RuntimeError: Cannot SIZE object 31 because it does not exist\n",
      "WARNING: Error drawing visual <Volume at 0x7fa91c6eb0d0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/app/backends/_qt.py\", line 846, in paintGL\n",
      "    self._vispy_canvas.events.draw(region=None)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 218, in on_draw\n",
      "    self._draw_scene()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 277, in _draw_scene\n",
      "    self.draw_visual(self.scene)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 315, in draw_visual\n",
      "    node.draw()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/visuals.py\", line 99, in draw\n",
      "    self._visual_superclass.draw(self)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/visuals/visual.py\", line 451, in draw\n",
      "    self._program.draw(self._vshare.draw_mode,\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/visuals/shaders/program.py\", line 102, in draw\n",
      "    Program.draw(self, *args, **kwargs)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/program.py\", line 526, in draw\n",
      "    canvas.context.flush_commands()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/context.py\", line 172, in flush_commands\n",
      "    self.glir.flush(self.shared.parser)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 579, in flush\n",
      "    self._shared.flush(parser)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 501, in flush\n",
      "    parser.parse(self._filter(self.clear(), parser))\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 819, in parse\n",
      "    self._parse(command)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 791, in _parse\n",
      "    ob.set_size(*args)  # Texture[1D, 2D, 3D], RenderBuffer\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 1626, in set_size\n",
      "    glTexImage3D(self._target, 0, internalformat, format,\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 1575, in glTexImage3D\n",
      "    _gl.glTexImage3D(target, level, internalformat,\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/OpenGL/latebind.py\", line 43, in __call__\n",
      "    return self._finalCall( *args, **named )\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/OpenGL/wrapper.py\", line 889, in wrapperCall\n",
      "    raise err\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/OpenGL/wrapper.py\", line 882, in wrapperCall\n",
      "    result = wrappedOperation( *cArguments )\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/OpenGL/error.py\", line 230, in glCheckError\n",
      "    raise self._errorClass(\n",
      "OpenGL.error.GLError: GLError(\n",
      "\terr = 1285,\n",
      "\tdescription = b'out of memory',\n",
      "\tbaseOperation = glTexImage3D,\n",
      "\tpyArgs = (\n",
      "\t\tGL_TEXTURE_3D,\n",
      "\t\t0,\n",
      "\t\tGL_LUMINANCE,\n",
      "\t\t1749,\n",
      "\t\t1628,\n",
      "\t\t859,\n",
      "\t\t0,\n",
      "\t\tGL_LUMINANCE,\n",
      "\t\tGL_BYTE,\n",
      "\t\tNone,\n",
      "\t),\n",
      "\tcArgs = (\n",
      "\t\tGL_TEXTURE_3D,\n",
      "\t\t0,\n",
      "\t\tGL_LUMINANCE,\n",
      "\t\t1749,\n",
      "\t\t1628,\n",
      "\t\t859,\n",
      "\t\t0,\n",
      "\t\tGL_LUMINANCE,\n",
      "\t\tGL_BYTE,\n",
      "\t\tNone,\n",
      "\t),\n",
      "\tcArguments = (\n",
      "\t\tGL_TEXTURE_3D,\n",
      "\t\t0,\n",
      "\t\tGL_LUMINANCE,\n",
      "\t\t1749,\n",
      "\t\t1628,\n",
      "\t\t859,\n",
      "\t\t0,\n",
      "\t\tGL_LUMINANCE,\n",
      "\t\tGL_BYTE,\n",
      "\t\tNone,\n",
      "\t)\n",
      ")\n",
      "WARNING: Error drawing visual <Volume at 0x7fa94c0b1e50>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/OpenGL/latebind.py\", line 43, in __call__\n",
      "    return self._finalCall( *args, **named )\n",
      "TypeError: 'NoneType' object is not callable\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/app/backends/_qt.py\", line 846, in paintGL\n",
      "    self._vispy_canvas.events.draw(region=None)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/util/event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 218, in on_draw\n",
      "    self._draw_scene()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 277, in _draw_scene\n",
      "    self.draw_visual(self.scene)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/canvas.py\", line 315, in draw_visual\n",
      "    node.draw()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/scene/visuals.py\", line 99, in draw\n",
      "    self._visual_superclass.draw(self)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/visuals/visual.py\", line 451, in draw\n",
      "    self._program.draw(self._vshare.draw_mode,\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/visuals/shaders/program.py\", line 102, in draw\n",
      "    Program.draw(self, *args, **kwargs)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/program.py\", line 526, in draw\n",
      "    canvas.context.flush_commands()\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/context.py\", line 172, in flush_commands\n",
      "    self.glir.flush(self.shared.parser)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 579, in flush\n",
      "    self._shared.flush(parser)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 501, in flush\n",
      "    parser.parse(self._filter(self.clear(), parser))\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 819, in parse\n",
      "    self._parse(command)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 789, in _parse\n",
      "    ob.set_data(*args)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 1642, in set_data\n",
      "    glTexSubImage3D(self._target, 0, x, y, z, format, gtype, data)\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/vispy/gloo/glir.py\", line 1609, in glTexSubImage3D\n",
      "    _gl.glTexSubImage3D(target, level, xoffset, yoffset, zoffset,\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/OpenGL/latebind.py\", line 47, in __call__\n",
      "    return self._finalCall( *args, **named )\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/OpenGL/wrapper.py\", line 889, in wrapperCall\n",
      "    raise err\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/OpenGL/wrapper.py\", line 882, in wrapperCall\n",
      "    result = wrappedOperation( *cArguments )\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py\", line 415, in __call__\n",
      "    return self( *args, **named )\n",
      "  File \"/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/OpenGL/error.py\", line 230, in glCheckError\n",
      "    raise self._errorClass(\n",
      "OpenGL.error.GLError: GLError(\n",
      "\terr = 1282,\n",
      "\tdescription = b'invalid operation',\n",
      "\tbaseOperation = glTexSubImage3D,\n",
      "\tpyArgs = (\n",
      "\t\tGL_TEXTURE_3D,\n",
      "\t\t0,\n",
      "\t\t0,\n",
      "\t\t0,\n",
      "\t\t0,\n",
      "\t\t1749,\n",
      "\t\t1628,\n",
      "\t\t859,\n",
      "\t\tGL_LUMINANCE,\n",
      "\t\tGL_FLOAT,\n",
      "\t\tarray([[[[0.31889397],\n",
      "         [0.31998834],\n",
      "         [0.30789575],\n",
      "         ...,\n",
      "         [0.28894523],\n",
      "         [0...,\n",
      "\t),\n",
      "\tcArgs = (\n",
      "\t\tGL_TEXTURE_3D,\n",
      "\t\t0,\n",
      "\t\t0,\n",
      "\t\t0,\n",
      "\t\t0,\n",
      "\t\t1749,\n",
      "\t\t1628,\n",
      "\t\t859,\n",
      "\t\tGL_LUMINANCE,\n",
      "\t\tGL_FLOAT,\n",
      "\t\tarray([[[[0.31889397],\n",
      "         [0.31998834],\n",
      "         [0.30789575],\n",
      "         ...,\n",
      "         [0.28894523],\n",
      "         [0...,\n",
      "\t),\n",
      "\tcArguments = (\n",
      "\t\tGL_TEXTURE_3D,\n",
      "\t\t0,\n",
      "\t\t0,\n",
      "\t\t0,\n",
      "\t\t0,\n",
      "\t\t1749,\n",
      "\t\t1628,\n",
      "\t\t859,\n",
      "\t\tGL_LUMINANCE,\n",
      "\t\tGL_FLOAT,\n",
      "\t\tarray([[[[0.31889397],\n",
      "         [0.31998834],\n",
      "         [0.30789575],\n",
      "         ...,\n",
      "         [0.28894523],\n",
      "         [0...,\n",
      "\t)\n",
      ")\n",
      "/home/jake/projects/mctnet/venv/lib/python3.8/site-packages/napari/_vispy/vispy_camera.py:109: RuntimeWarning: divide by zero encountered in true_divide\n",
      "  zoom = np.min(canvas_size / scale)\n"
     ]
    }
   ],
   "source": [
    "img.affine"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "ann.affine"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Now let's do a plot to make sure everything looks ok"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "subject = tio.Subject(\n",
    "    mct=img,\n",
    "    labels=ann,\n",
    "    id=id\n",
    ")\n",
    "subject.plot()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Now that we've generated our labels, let's save them to disk so they can be loaded by our model for training."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "ann.save('_label.nii.gz')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Now we can load this data quickly during training and testing. This can be done with the approach below."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "img = tio.ScalarImage(\n",
    "    \n",
    ")\n",
    "ann = tio.LabelMap(\n",
    "    'data/'+ id + '/' + id + '_label.nii.gz',\n",
    "    affine=img.affine\n",
    ")\n",
    "subject = tio.Subject(\n",
    "    mct=img,\n",
    "    labels=ann,\n",
    "    id=id\n",
    ")\n",
    "subject.plot()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "f726fa9e3d96265230c4503e543f5c3f73ae5ded033c480caee9e2a2a13a4b04"
  },
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
